# Generated by Django 4.2.3 on 2023-07-23 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstdatabase',
            name='entry_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 22, 50, 3, 709046, tzinfo=datetime.timezone.utc), verbose_name='Date entry created'),
        ),
        migrations.AddField(
            model_name='firstdatabase',
            name='entry_type',
            field=models.CharField(default='Supertype', max_length=100),
        ),
        migrations.CreateModel(
            name='SecondDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling', models.CharField(max_length=100)),
                ('super_number', models.IntegerField(default=0)),
                ('first', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.firstdatabase')),
            ],
        ),
    ]
