# Generated by Django 4.2.4 on 2023-08-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_firstdatabase_entry_created_firstdatabase_entry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstdatabase',
            name='entry_created',
            field=models.DateTimeField(verbose_name='Date entry created'),
        ),
    ]
